exports.create = {
	User: [ { "name.first": "James", "name.second": "Powell","email": "tutor.liaison.officer@students4students.org.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": true},
 { "name.first": "Eleanor", "name.second": "Smyth","email": "eleanor.smyth@trinity.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Cody", "name.second": "Sands","email": "cordelia.sands@lmh.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Matt", "name.second": "Cockrill","email": "matthew.cockerill@seh.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Abigail", "name.second": "Blucher-Altona","email": "abigail.blucher-altona@st-hughs.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": true},
 { "name.first": "Charis", "name.second": "Bridger Staatz ","email": "charisbs@hotmail.co.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Rose", "name.second": "Lynch","email": "rose.lynch@univ.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Allan", "name.second": "Ross","email": "allan.ross@st-hughs.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Ben", "name.second": "Woods","email": "benjamin.woods@seh.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Beth", "name.second": "Archibald","email": "beth.archibald@st-hildas.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Ben", "name.second": "Gibbons","email": "benjamin.gibbons@st-hughs.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Hannah", "name.second": "Partington","email": "hannah.partington@stcatz.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Steph", "name.second": "Hawthorn","email": "stephanie.hawthorn@oriel.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Millie", "name.second": "McLuskie","email": "millie.mcluskie@pmb.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Anna", "name.second": "Shepherd","email": "anna.shepherd@chch.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Lydia", "name.second": "Kanari-Naish","email": "lydia.kanari-naish@oriel.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Alice", "name.second": "Pickethall","email": "alice.pickthall@stcatz.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Aoife", "name.second": "Hyde","email": "aoife.hyde@stcatz.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Claudette", "name.second": "Hewitt","email": "claudette.hewitt@lmh.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Rachel", "name.second": "Garwood","email": "rachel.garwood@st-hildas.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Emma", "name.second": "Carr","email": "emmacarr18@gmail.com","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Joe", "name.second": "Kelly","email": "joseph.kelly@lincoln.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false},
 { "name.first": "Sara", "name.second": "Brown","email": "sara.brown@lmh.ox.ac.uk","password": process.env.DEFAULT_PASSWORD, "isAdmin": false}]
};
